ansys/pysimai

src/ansys/simai/core/data/workspaces.py
=> Fix ModelManifest available-post-processings

README.rst
[sc-16695]
This PR adds install directions on Windows for the developer track
=> Direction for Windows-developer mode

doc/source/api_reference/projects.rst, src/ansys/simai/core/api/project.py, src/ansys/simai/core/data/projects.py, tests/test_projects.py
=> Adding is_trainable and get_variables in Project

src/ansys/simai/core/api/training_data.py, src/ansys/simai/core/data/training_data.py, tests/test_training_data.py
[sc-17799]
fix for pysimai bug on get_subset(); tested on dev1
=> Bug/sc 17799/investigate potential get subset pysimai

.github/workflows/ci_cd.yml, src/ansys/simai/core/data/projects.py
=> fix: CI not running test with specified python

src/ansys/simai/core/data/predictions.py
=> fix prediction list without current_workspace being set

src/ansys/simai/core/api/training_data.py, src/ansys/simai/core/data/training_data.py, src/ansys/simai/core/data/types.py, tests/test_training_data.py
=> Allow assign subset to None; Retire: Ignored and Validation

doc/source/user_guide/training.rst
Description:
Adding a note as notification on the date the feature of training with last configuration is supported.
Story: sc-19138
=> [Documentation] Note on training using last config

src/ansys/simai/core/data/training_data.py
This option could cause confusion and it has been decided to remove it
=> chore: remove compute argument from td upload

src/ansys/simai/core/data/global_coefficients_requests.py, src/ansys/simai/core/data/post_processings.py, src/ansys/simai/core/utils/numerical.py, tests/test_numerical_utils.py
Less naive implementation that we can reuse in the future
=> fix: NaN and inf conversion

src/ansys/simai/core/data/geometries.py
Changed from workspace_id to workspace a while ago but doc was never updated
=> fix: geometry.upload correctly documents workspace arg

src/ansys/simai/core/data/types.py, src/ansys/simai/core/utils/requests.py
https://mypy.readthedocs.io/en/stable/literal_types.html#literal-types
=> tweak: small typing improvement

doc/source/api_reference/post_processings.rst, doc/source/api_reference/selections.rst, src/ansys/simai/core/__init__.py, src/ansys/simai/core/data/post_processings.py, src/ansys/simai/core/data/selection_post_processings.py, tests/test_post_processing_actions.py, tests/test_post_processing_export.py, tests/test_post_processings.py, tests/test_post_processings_results.py, tests/test_post_processings_run.py, tests/test_selection_post_processings.py
Renaming SurfaceEvol to SurfaceEvolution and testing the feature
Story : [sc-10207]
=> feat: reintroduce surface evolution pp

LICENSE
Update the license file.
Fix #120
=> CHORE: Update LICENSE

src/ansys/simai/core/api/training_data.py, src/ansys/simai/core/api/training_data_part.py, src/ansys/simai/core/data/training_data.py, tests/test_training_data.py
SDK is still using endpoints we renamed loong ago
=> stop using deprecated endpoints

.github/workflows/ci_cd.yml, src/ansys/simai/core/api/training_data.py, src/ansys/simai/core/data/training_data.py, src/ansys/simai/core/data/types.py, src/ansys/simai/core/utils/pagination.py, tests/test_training_data.py
Because waiting for potentially tens of thousands of objects to be fetched into a list isn't great UX.
With this change one can still to `len(clt.training_data.iter())`, it will just take 1/100th of the time to do so.
=> add clt.training_data.iter()

src/ansys/simai/core/data/base.py
=> Fix: turn log from error to debug when receiving event that the sdk don't deal with

src/ansys/simai/core/api/mixin.py
=> tweak: include python version in user_agent

doc/source/user_guide/data_exploration.rst, src/ansys/simai/core/data/model_configuration.py, src/ansys/simai/core/data/post_processings.py
Fix multiple outdated examples and references.
=> docs: fix outdated examples and references

src/ansys/simai/core/data/optimizations.py
Optimization can be run using both parametric and non-parametric methods. This updates the documentation examples for both approaches.
=> docs: update code examples for the optimization parametric and non parametric

src/ansys/simai/core/data/optimizations.py, tests/test_optimizations.py
Add various validations to enforce checks for running parametric and non-parametric optimizations.
=> feat: improve check for parametric and non parametric optimizations

AUTHORS
=> chore: updating AUTHORS file

src/ansys/simai/core/data/optimizations.py, tests/test_optimizations.py
Add axial_symmetry parameter to non parametric optimization
=> feat: add axial_symmetry parameter to non parametric optimization

.github/workflows/ci_cd.yml
Should solve : 
- https://github.com/ansys/pysimai/issues/177
- https://github.com/ansys/pysimai/issues/176
- https://github.com/ansys/pysimai/issues/166
=> chore: update CI/CD workflow
